export const TABLE_SORT = 'TABLE_SORT';
export const TABLE_SORT_CURRENT = 'TABLE_SORT_CURRENT';
export const TABLE_SORT_CLEAR = 'TABLE_SORT_CLEAR';
export const INPUT_SEARCH_VALUE = 'INPUT_SEARCH_VALUE';
export const SEARCH_ROWS = 'SEARCH_ROWS';
